CREATE TABLE comments
(
	comment_id VARCHAR(32) NOT NULL,
	image_id VARCHAR(32) NOT NULL,
	user_id VARCHAR(32) NOT NULL,
	comment VARCHAR(300) NOT NULL,
	date VARCHAR(32) NOT NULL,
	date_unix VARCHAR(32) NOT NULL,
	
	PRIMARY KEY(comment_id),
	CONSTRAINT FOREIGN KEY(user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;