CREATE TABLE images
(
	id INT(11) NOT NULL,
	name VARCHAR(100) NOT NULL,
	user_id INT(11) NOT NULL,
	description VARCHAR(300) NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	privacy TINYINT(1) NOT NULL,
	directory VARCHAR(200) NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);